#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
$HOME/.config/polybar/launch.sh &

# Dual monitor
if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
	xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI\-A\-0 --mode 1366x768 --right-of eDP
	bspc monitor HDMI\-A\-0 -d VI VII VIII IX X
fi

# Primary monitor
bspc monitor eDP -d I II III IV V


# window options
bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# App rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
